const $=s=>document.querySelector(s);const colors={full:'#0a8f5b',warning:'#ffb000',urgent:'#7146d9',empty:'#f04444'};
let points=JSON.parse(localStorage.getItem('pati-points')||'null')||[
{id:1,code:'HAYSEV-01',name:'HaySev Topluluk Odası',area:'Yakut Çarşı karşısı',x:61.3,y:26.5,status:'full',time:'2 saat önce',animals:'8-12 kedi',note:'HaySev kulübesinin yanındaki ağaçlık alan.'},
{id:2,code:'ILETISIM-01',name:'İletişim Fakültesi Bahçesi',area:'İletişim Fakültesi',x:29.2,y:46.5,status:'warning',time:'31 saat önce',animals:'6-9 kedi',note:'Fakülte girişinin sol tarafındaki yeşil alan.'},
{id:3,code:'KYK-KIZ-01',name:'KYK Kız Yurtları Noktası',area:'Yurtlar Bölgesi',x:55.8,y:75.5,status:'urgent',time:'55 saat önce',animals:'10-15 kedi',note:'Yurtların kuzey girişindeki yürüyüş yolu yanı.'}];
const labels={full:'Dolu',warning:'Azalıyor',urgent:'Kontrol edilmeli',empty:'Boş olabilir'};let volunteer=JSON.parse(localStorage.getItem('pati-volunteer')||'null');
function icon(n){return `<span class="ico">${n}</span>`}function save(){localStorage.setItem('pati-points',JSON.stringify(points))}
function home(){app.innerHTML=`<main class="shell"><header><div><small>AKDENİZ ÜNİVERSİTESİ</small><h1>Pati Haritası</h1><p>Kampüsteki dostlarımız için birlikte.</p></div><button class="iconBtn">🔔</button></header><section class="stats">${[[points.length,'Nokta'],[1,'Bugün'],[points.filter(x=>x.status==='urgent').length,'Kontrol'],[points.filter(x=>x.status==='empty').length,'Acil']].map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</section><section class="mapSec"><div class="sectionHead"><div><h2>Kampüs haritası</h2><p>Pati işaretlerine dokunarak incele</p></div><button id="expand">⛶ Tam ekran</button></div>${mapHTML(false)}<p class="note">* Bu harita, kampüsteki besleme noktalarının takibi amacıyla hazırlanmıştır; gerçek ölçek ve mesafeleri yansıtmaz.</p></section><section><h2>Hızlı işlemler</h2><div class="quick"><button id="qr">▣<b>QR kodu tara</b><span>Noktayı hızlı güncelle</span></button><button id="urgent">⚠<b>Acil noktalar</b><span>Öncelikli alanları gör</span></button></div></section><nav>${[['⌂','Ana'],['◇','Harita'],['▣','QR'],['⚠','Acil'],['♙','Profil']].map(x=>`<button data-nav="${x[1]}"><i>${x[0]}</i><span>${x[1]}</span></button>`).join('')}</nav></main>`;wireMap($('.map'));$('#expand').onclick=fullMap;$('#qr').onclick=qr;document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>b.dataset.nav==='Harita'?fullMap():b.dataset.nav==='QR'?qr():b.dataset.nav==='Profil'?moderatorLogin():null)}
function mapHTML(full){return `<div class="map ${full?'full':''}"><div class="canvas"><img src="/kampus-haritasi.png?v=clean-1" draggable="false">${points.map(p=>`<button class="pin" data-id="${p.id}" style="left:${p.x}%;top:${p.y}%;background:${colors[p.status]}">🐾</button>`).join('')}</div><div class="controls"><button data-zoom="in">＋</button><button data-zoom="out">−</button><button data-reset>1×</button>${full?'<button data-close>×</button>':''}</div>${full?'<div class="legend"><span><i style="background:#0a8f5b"></i>Dolu</span><span><i style="background:#ffb000"></i>Azalıyor</span><span><i style="background:#7146d9"></i>Kontrol</span></div>':''}</div>`}
function wireMap(el){let z=1,x=0,y=0,pointers=new Map(),gesture={};const canvas=el.querySelector('.canvas');const draw=()=>canvas.style.transform=`translate3d(${x}px,${y}px,0) scale(${z})`;el.onpointerdown=e=>{if(e.target.closest('button'))return;e.preventDefault();el.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});let a=[...pointers.values()];if(a.length===1)gesture={sx:a[0].x,sy:a[0].y,x,y};if(a.length===2)gesture={distance:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),z,x,y}};el.onpointermove=e=>{if(!pointers.has(e.pointerId))return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});let a=[...pointers.values()];if(a.length===1&&z>1){x=gesture.x+a[0].x-gesture.sx;y=gesture.y+a[0].y-gesture.sy;draw()}if(a.length===2){z=Math.max(1,Math.min(4,gesture.z*Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)/gesture.distance));draw()}};el.onpointerup=e=>pointers.delete(e.pointerId);el.querySelector('[data-zoom=in]').onclick=()=>{z=Math.min(4,z+.35);draw()};el.querySelector('[data-zoom=out]').onclick=()=>{z=Math.max(1,z-.35);if(z===1)x=y=0;draw()};el.querySelector('[data-reset]').onclick=()=>{z=1;x=y=0;draw()};el.querySelectorAll('.pin').forEach(b=>b.onclick=e=>{e.stopPropagation();details(+b.dataset.id)});el.querySelector('[data-close]')?.addEventListener('click',()=>el.parentElement.remove())}
function fullMap(){document.body.insertAdjacentHTML('beforeend',`<div class="overlay">${mapHTML(true)}</div>`);wireMap($('.overlay .map'))}
function details(id){let p=points.find(x=>x.id===id);document.body.insertAdjacentHTML('beforeend',`<div class="shade"></div><aside class="sheet"><button class="x">×</button><span class="badge" style="color:${colors[p.status]}">${labels[p.status]} · ${p.time}</span><h2>${p.name}</h2><p>📍 ${p.area}</p><div class="info"><b>🐾 ${p.animals}</b><b>🥣 Mama noktası</b></div><div class="location"><small>KONUM TARİFİ</small>${p.note}</div><h3>Hızlı güncelleme</h3><div class="actions"><button data-s="full">Mama bıraktım</button><button data-s="full">Su doldurdum</button><button data-s="full">Mama hâlâ var</button><button data-s="empty">Mama bitmiş</button></div></aside>`);const close=()=>{$('.shade').remove();$('.sheet').remove()};$('.x').onclick=close;$('.shade').onclick=close;document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>volunteerGate(()=>{p.status=b.dataset.s;p.time='Şimdi';save();close();home()}))}
function volunteerGate(done){if(volunteer)return done();document.body.insertAdjacentHTML('beforeend',`<div class="modal"><form class="card"><button type="button" class="x">×</button><small>HIZLI KATILIM</small><h2>Adını paylaş</h2><p>Üyelik gerekmiyor. Adın yapılan güncellemenin yanında yalnızca baş harfle gösterilecek.</p><input name="name" required placeholder="Ad"><input name="surname" required placeholder="Soyad"><button class="submit">Devam et</button></form></div>`);$('.modal .x').onclick=()=>$('.modal').remove();$('.card').onsubmit=e=>{e.preventDefault();volunteer={name:e.target.name.value,surname:e.target.surname.value};localStorage.setItem('pati-volunteer',JSON.stringify(volunteer));$('.modal').remove();done()}}
function qr(){document.body.insertAdjacentHTML('beforeend',`<div class="scanner"><button class="x">×</button><small>HIZLI GÜNCELLEME</small><h2>QR kodu tara</h2><div class="scanbox">▣</div><p>Kamera entegrasyonu sonraki veritabanı sürümünde etkinleştirilecek.</p><input id="code" placeholder="Örn. HAYSEV-01"><button id="openCode">Kodu aç</button></div>`);$('.scanner .x').onclick=()=>$('.scanner').remove();$('#openCode').onclick=()=>{let p=points.find(x=>x.code===$('#code').value.trim().toUpperCase());if(p){$('.scanner').remove();details(p.id)}}}
function moderatorLogin(){document.body.insertAdjacentHTML('beforeend',`<div class="modal"><form class="card"><button type="button" class="x">×</button><small>YETKİLİ ERİŞİMİ</small><h2>Moderatör girişi</h2><p>Yönetim paneli bu temiz temelde kapalıdır. Güvenli sunucu girişi bir sonraki adımda eklenecek.</p><button type="button" class="submit" disabled>Yakında</button></form></div>`);$('.modal .x').onclick=()=>$('.modal').remove()}
home();
