-- TEMIZ KURULUM / MEVCUT TABLOLARLA UYUMLU MIGRATION
alter table public.profiles add column if not exists avatar_id text default 'avatar-04';

create table if not exists public.feeding_points(
 id bigint generated by default as identity primary key,
 name text not null, area text not null, x numeric not null, y numeric not null,
 status text not null default 'full', animals text, location_description text,
 is_active boolean not null default true, created_by uuid references auth.users(id),
 updated_by uuid references auth.users(id), created_at timestamptz default now(), updated_at timestamptz default now()
);
alter table public.feeding_points enable row level security;
drop policy if exists "public read points" on public.feeding_points;
create policy "public read points" on public.feeding_points for select using(is_active=true);

do $$ begin
 if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='feeding_points') then alter publication supabase_realtime add table public.feeding_points; end if;
end $$;
