'use client';
import {useState} from 'react';
import {Bell, CircleAlert, Droplets, Expand, Home, Map, MapPin, Minus, PawPrint, Plus, QrCode, ScanLine, UserRound, Utensils, X} from 'lucide-react';
const initial=[
{id:1,name:'HaySev Topluluk Odası',area:'Yakut Çarşı karşısı',x:61.3,y:26.5,status:'full',label:'Dolu',updated:'2 saat önce',animals:'8-12 kedi',bowls:'2 mama kabı',water:'Su kabı mevcut',directions:'HaySev kulübesinin yanındaki ağaçlık alan.'},
{id:2,name:'İletişim Fakültesi Bahçesi',area:'İletişim Fakültesi',x:29.2,y:46.5,status:'warning',label:'Azalıyor',updated:'31 saat önce',animals:'6-9 kedi',bowls:'1 mama kabı',water:'Su durumu bilinmiyor',directions:'Fakülte girişinin sol tarafındaki yeşil alan.'},
{id:3,name:'KYK Kız Yurtları Noktası',area:'Yurtlar Bölgesi',x:55.8,y:75.5,status:'urgent',label:'Kontrol edilmeli',updated:'55 saat önce',animals:'10-15 kedi',bowls:'2 mama kabı',water:'Su kabı mevcut',directions:'Yurt kümesinin kuzey girişindeki yürüyüş yolunun yanı.'}
];
const colors={full:'#14945f',warning:'#f0a51a',urgent:'#6c3bb8',empty:'#df3939'};
function MapView({points,onPoint,full,onClose}){const [zoom,setZoom]=useState(1);return <div className={full?'map full':'map'}><div className="mapInner" style={{transform:`scale(${zoom})`}}><img src="/akdeniz-pati-haritasi.png" alt="Akdeniz Üniversitesi kampüs haritası"/>{points.map(p=><button className="pin" key={p.id} style={{left:p.x+'%',top:p.y+'%',background:colors[p.status]}} onClick={()=>onPoint(p)}><PawPrint size={15}/></button>)}</div><div className="mapTools">{full&&<button onClick={onClose}><X/></button>}<button onClick={()=>setZoom(z=>Math.min(3,z+.25))}><Plus/></button><button onClick={()=>setZoom(z=>Math.max(1,z-.25))}><Minus/></button></div>{!full&&<div className="mapBar"><span><PawPrint size={15}/> 3 örnek nokta</span><button onClick={onClose}><Expand size={16}/> Büyüt</button></div>}</div>}
export default function Page(){const [points,setPoints]=useState(initial);const [selected,setSelected]=useState(null);const [full,setFull]=useState(false);const [scan,setScan]=useState(false);const update=(kind)=>{const good=kind!=='empty';setPoints(x=>x.map(p=>p.id===selected.id?{...p,status:good?'full':'empty',label:good?'Dolu':'Boş olabilir',updated:'Şimdi'}:p));setSelected(p=>({...p,status:good?'full':'empty',label:good?'Dolu':'Boş olabilir',updated:'Şimdi'}));};return <main><div className="phone"><header><div><small>AKDENİZ ÜNİVERSİTESİ</small><h1>Pati Haritası</h1><p>Kampüsteki dostlarımız için birlikte.</p></div><button className="icon"><Bell/></button></header><section className="stats">{[['3','Nokta'],['1','Bugün'],['1','Kontrol'],['0','Acil']].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</section><section><div className="title"><div><h2>Kampüs haritası</h2><p>Pati işaretlerine dokunarak incele</p></div></div><MapView points={points} onPoint={setSelected} full={false} onClose={()=>setFull(true)}/></section><section><h2>Hızlı işlemler</h2><div className="quick"><button onClick={()=>setScan(true)}><ScanLine/><b>QR kodu tara</b><span>Noktayı hızlı güncelle</span></button><button><CircleAlert/><b>Acil noktalar</b><span>Öncelikli alanları gör</span></button></div></section><nav>{[[Home,'Ana'],[Map,'Harita'],[QrCode,'QR'],[CircleAlert,'Acil'],[UserRound,'Profil']].map(([I,t])=><button key={t} onClick={()=>t==='QR'&&setScan(true)}><I/><span>{t}</span></button>)}</nav>{full&&<div className="overlay"><MapView points={points} onPoint={setSelected} full onClose={()=>setFull(false)}/></div>}{selected&&<><div className="shade" onClick={()=>setSelected(null)}/><div className="sheet"><div className="handle"/><button className="close" onClick={()=>setSelected(null)}><X/></button><span className="badge" style={{color:colors[selected.status]}}>{selected.label} · {selected.updated}</span><h2>{selected.name}</h2><p><MapPin size={15}/> {selected.area}</p><div className="info"><div><PawPrint/>{selected.animals}</div><div><Utensils/>{selected.bowls}</div><div><Droplets/>{selected.water}</div></div><div className="directions"><small>KONUM TARİFİ</small>{selected.directions}</div><h3>Hızlı güncelleme</h3><div className="actions"><button onClick={()=>update('food')}>Mama bıraktım</button><button onClick={()=>update('water')}>Su doldurdum</button><button onClick={()=>update('still')}>Mama hâlâ var</button><button onClick={()=>update('empty')}>Mama bitmiş</button></div></div></>}{scan&&<div className="scanner"><button onClick={()=>setScan(false)}><X/></button><small>HIZLI GÜNCELLEME</small><h2>QR kodu tara</h2><div className="scanbox"><ScanLine size={52}/></div><p>Mama noktasındaki QR kodu çerçevenin içine yerleştir.</p></div>}</div></main>}
